-- RESGATA DADOS DA COLUNA POREM NÃO REPETE VALORES IDENTICOS(IGUAIS)

SELECT DISTINCT Country FROM Customers;


-- RESGATA A QUANTIDADE (FAZ UM CONTADOR)

SELECT COUNT(DISTINCT Country) FROM Customers;